{% set name = "google-crc32c" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/google_crc32c-{{ version }}.tar.gz
  sha256: 6eceb6ad197656a1ff49ebfbbfa870678c75be4344feb35ac1edf694309413dc
build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - libcrc32c
    - setuptools
    - wheel
  run:
    - python
    - importlib-resources >=1.3 # [py<39]

test:
  source_files:
    - tests
  requires:
    - python
    - pip
    - pytest
  imports:
    - google_crc32c
  commands:
    - python -m pip check
    - pytest


about:
  home: https://github.com/googleapis/python-crc32c
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  licenes_url: https://github.com/googleapis/python-crc32c/blob/main/LICENSE
  summary: Python wrapper for a hardware-based implementation of the CRC32C hashing algorithm

  description: |
    google-crc32c wraps the libcrc32c
    <https://github.com/google/crc32c> package, which is a hardware-based
    implementation of the CRC32C hashing algorithm.
  doc_url: https://github.com/googleapis/python-crc32c
  dev_url: https://github.com/googleapis/python-crc32c

extra:
  recipe-maintainers:
    - tswast
